# Site
name: "Miral Achmed"
description: "My Simple Personal Blog"
meta_description: "Simple Personal Blog by Miral Achmed"
logo: 'assets/images/miral-achmed-1.png'
favicon: 'favicon.ico'
url: 'http://achmiral.id'
baseurl: ''
google_analytics: 'UA-86909679-1'
disqus: 'achmiral-id'
mailchimp-list: ''
permalink: /:year/:month/:day/:title

# Authors
authors:
  miral:
    name: Miral Achmed
    display_name: Miral Achmed
    gravatar: 3654d753e5a623523e5190e7b3ec59e5
    email: miral.achmed@gmail.com
    web: achmiral.id
    twitter: https://twitter.com/achmiral
    instagram: https://instagram.com/achmiral
    description: "Author of achmiral.id, FPV Racing Drone Pilot, Rubyist, Currently Student at AMIKOM Yogyakarta"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-compose
  - jemoji
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge